# Site settings
title: "Craig P Stringer CV"
description: "Office Administrator"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Craig P. Stringer"
resume_title:                   "Office Administrator with Vast Experience in Banking and Recruitment"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "craigstringer930@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "07821 085265 / 0114 2334421"
resume_contact_address:         "32 Stanwood Avenue, Stannington Sheffield, S65HY"

resume_header_contact_info:     "32 Stanwood Avenue, Stannington Sheffield, S65HY • 07821 085265 • craigstringer930@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Currently looking for a career in Admin/Business Support in a fast paced, challenging work environment.
Have a tendency to work with a pro-active and flexible mind-set at all times in order to obtain the best results possible, as well as being extremely organised and self-motivated to meet tight deadlines. Very capable of working on own initiative or with others as the situation requires it. Excellent team working and communication skills; able to collaborate and communicate very well with a wide range of people in order to complete tasks. Have exceptional experience working in Administration and Data Entry as a Recruitment Administrator at Royal Mail, as well as a Probate Officer/Mortgage Processor at HSBC.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/jglovier/resume-template"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/craig-stringer-066726114/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
